// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz-Gc8zhVOlLLuycNa4DKIuaXe6EqMrvs',
    appId: '1:558415758788:ios:3239eb58109cc919419091',
    messagingSenderId: '558415758788',
    projectId: 'sihapp-66785',
    storageBucket: 'sihapp-66785.firebasestorage.app',
    iosClientId: '558415758788-tqpje6fn3861g9oco2mducu4da9sqc4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.sih',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Jmcq6wun8zkLq3Se3Ovy3tmZ0EOkW0s',
    appId: '1:558415758788:web:fbec8abeb09157b2419091',
    messagingSenderId: '558415758788',
    projectId: 'sihapp-66785',
    authDomain: 'sihapp-66785.firebaseapp.com',
    storageBucket: 'sihapp-66785.firebasestorage.app',
    measurementId: 'G-KYZ1TCWSM4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz-Gc8zhVOlLLuycNa4DKIuaXe6EqMrvs',
    appId: '1:558415758788:ios:3239eb58109cc919419091',
    messagingSenderId: '558415758788',
    projectId: 'sihapp-66785',
    storageBucket: 'sihapp-66785.firebasestorage.app',
    iosClientId: '558415758788-tqpje6fn3861g9oco2mducu4da9sqc4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.sih',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5XT9mwMetQrn3dtMobse01mBtC93AYDY',
    appId: '1:558415758788:android:12245179fed1d6b2419091',
    messagingSenderId: '558415758788',
    projectId: 'sihapp-66785',
    storageBucket: 'sihapp-66785.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Jmcq6wun8zkLq3Se3Ovy3tmZ0EOkW0s',
    appId: '1:558415758788:web:9e4f4adf090ea0a8419091',
    messagingSenderId: '558415758788',
    projectId: 'sihapp-66785',
    authDomain: 'sihapp-66785.firebaseapp.com',
    storageBucket: 'sihapp-66785.firebasestorage.app',
    measurementId: 'G-7JKHKPVYDK',
  );

}